version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
   
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
